# https://beta.ruff.rs
name: python
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install --user --upgrade setuptools wheel

      - name: Build
        run: |
          python3 setup.py sdist bdist_wheel

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v7
          append_body: true
          body_path: README.md
          files: |
            dist/*
